### ISSUE TITLE
Random reboots without ngfxsubmit=0

### ISSUE THREAD

**Issue by zaubara** [lvs1974/NvidiaGraphicsFixup#11]
Hey, first off thanks for the great patches - indeed the latest commits made the OS incredibly fluid!

However if on my system I use the workaround, I get random system reboots - screen goes black, and then hangs (with looping sound) or instantly reboots.
Console doesn't report anything too convincing regarding the crash, and there's no report the problem popup on reboot either.
The issue goes away when booting with ngfxsubmit=0. Never messed around with Metal.

Is there anything I can do or provide you with to tackle the issue?

**Comment by vit9696** [comment]
From what I can tell after a couple of days of running the fix, there are no reboots or crashes with the official driver. And so far I haven't seen any issues with the web drivers either (with a reasonably large GPU model list). From the nature of the fix I have to admit that it is hardly possible for it to cause the reboots, or rather it would have been the same in 10.12.x days.

What I could suspect is your driver installation, due to a common approach of "solving" driver problems with a driver downgrade it could be that you have some binary mixture in your system, old drivers (this is fatal), or some insane setup. Perhaps, it is better to retry on the clean system with the official binaries once they are out. It could also be that some buggy app is relevant.
