### ISSUE TITLE
Stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0

### ISSUE THREAD

**Issue by MetalBreaker** [lvs1974/NvidiaGraphicsFixup#3]
Hi,

I noticed some weird behavior with macOS High Sierra. This system was working just fine on Sierra 10.12.5, until I decided to update to High Sierra (10.13.3). The upgrade process went mostly fine I believe, but it got stuck in an infinite spinning wheel which would just keep overlapping. I went into verbose mode, and sure enough, I found "IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0" repeating over and over along with ACM errors... I'm really lost right now. I can boot in recovery mode and safe mode just fine, when the graphics drivers aren't loaded. Web drivers aren't installed. I installed this kext, but it didn't fix the issue. I tried deleting the native graphics drivers from macOS and installing web drivers, but it didn't help. On boot-up, the CUDA preference pane opens and says "Update required", even though a newer version can't be found.

SMBIOS: iMac13,1
Graphics card: ASUS GT630-2GD3 (It's a Fermi card and it needs injection, so I modified my DSDT. Full graphics acceleration worked in Sierra. No Clover injection.)
CPU: Intel Core i3-3210, iGPU disabled in UEFI

Any help would be appreciated.
Thank you for your time!

**Comment by arsradu** [comment]
Funny I posted the same issue last week. :)) Not sure you already seen that or not but anyway.

Alright, let's try to get this fixed for you, as well.

1. Clean install is the word of wisdom here. Clean installation of the driver, of course. Not the OS.
I had a previously installed driver, and just added nvidiagraphicsfixup kext v1.2.3 in Clover/kexts/Other and...it made no difference. So there might be more to it.
2. Use [THIS](https://github.com/Benjamin-Dobell/nvidia-update) script to both uninstall and reinstall the driver (I would suggest sticking to the recommended version .106 for High Sierra).
3. SIP disabled! I know it says it works with SIP enabled, as well. But it just didn't work for me. So keep that in mind.

**Comment by MetalBreaker** [comment]
Hi! Thanks for answering.

Yes, I saw your issue! It gave me motivation, a feeling that I wasn't alone with this issue, but I got discouraged when I learned the issue happens with native drivers as well...
Sadly... I couldn't fix it. 
I tried doing a clean install of the web driver. Nothing.
I tried using the script you proposed with SIP disabled. The script succeeds but... I get the same issue.

This keeps repeating over and over...
![img_5307](https://user-images.githubusercontent.com/6906399/37556424-00bd77ca-29f6-11e8-96b0-1ad032283468.JPG)


Thanks again!

**Comment by arsradu** [comment]
You're definitely not the only one. :) There are a lot of people with the same issue.

BUT, what's interesting is that it doesn't work for you... You're using version 1.2.3 of this kext, right? I never had this issue with native drivers.
Sorry, not trying to be redundant. Just to double check these things since they might be important.

**Comment by vit9696** [comment]
The issue happens when there are 2 active GPUs with any drivers (both native and web), and it is not relevant to IntelGraphicsFixup or NvidiaGraphicsFixup. This appears to be a bug with 10.13, yet I have never investigated what actually causes it. From my experience even a "disabled" IGPU with a frame with connectors can cause it, for example.

**Comment by MetalBreaker** [comment]
Huh. How would I go about actually disabling the iGPU, then? DSDT?

**Comment by arsradu** [comment]
My Intel GPU is enabled. And I now don't have this issue anymore. So...I'm not sure what the hell is causing this... I just know that it never occurred with supported GPUs and for as far as I know, the SMBIOS has something to do with it too. For example iMac17,1 is one of them. Could also be a bug with 10.13...but then again, same OS, supported GPU, never had this issue.

What I would try, is this (in case you haven't already). And it might be important to actually do it this way.

1. make sure you're booting from the correct drive. UEFI is smart, but also, kinda stupid. And if it can't boot from one drive, it will automatically try the other ones. If you have multiple drives, it's important that you use the correct one, especially if you have different kexts on different drives.
2. on Clover GUI, press F11
3. boot into the OS with nv_disable=1.
4. uninstall the driver (from System Preferences)
5. REBOOT
6. on reboot, you shouldn't need to add nv_disable to boot, since there is no "NV" driver to boot in the first place.
7. install driver 106 using that script (once again: SIP DISABLED. Completely!).
8. REBOOT

That's pretty much all I've done... And now it works. 
If you can boot successfully (which I hope you will) see if you're booting using the Nvidia Driver, or Apple Driver (you can see it in the top panel if you have Nvidia Driver Manager set up to appear there).

**Comment by MetalBreaker** [comment]
Since there's no way I can disable my iGPU, I will try to embrace it and enable it. Here goes nothing...

(thanks for your continued help!)

**Comment by arsradu** [comment]
Well, I'm personally not sure it is related to the iGPU....since, as I said, same exact setup, same OS, with supported GPU, I have no issue, with unsupported GPU, I've got that issue. BUT not always. The hardware is the same, the OS is the same. The only thing different in my case were the way I installed the Nvidia Driver, and the fact that now I have NvidiaGraphicsFixup kext 1.2.3 which might or might not actually help with this issue.

**Comment by MetalBreaker** [comment]
Maybe it's something with the microarchitecture... I'm on Ivy Bridge.

**Comment by arsradu** [comment]
Hmmm....could be....but then again, I'm not. And I've had the exact same issue. Maaaaybe there are multiple causes for the same issue...

**Comment by MetalBreaker** [comment]
One thing I haven't tried is resetting the NVRAM, but I have no idea why it would cause issues...

**Comment by arsradu** [comment]
For as far as I know, it can cause issues, if you're booting with old information. Also, it doesn't cost anything to press F11. So..you might as well do it anyway. :)

**Comment by MetalBreaker** [comment]
I tried everything you said, carefully followed step by step... It still doesn't work. I just want to give up, but I can't.. It worked just fine on Sierra 10.12.5, I'm baffled. I have no backup. Kill me.

**Comment by arsradu** [comment]
If it worked with Sierra, I see no reason why it wouldn't work with High Sierra. Have you tried a different SMBIOS? Have you tried a different port on your GPU? Or a different monitor (if you have a another one)?
Could you upload your cleaned up (no serials) Clover config here for analysis?
Another thing you could try is to reinstall the OS (High Sierra). Preferably a clean install. Backup only the important stuff (no app data and things like that, just the documents you need) and reinstall. See if that works.
Also, are you using OSXAptioFixDrv3? Are you using EmuVariable (you shouldn't need it, for as far as I know) or CsmVideoDxe?
You could also try updating your FakeSMC kext, in case you haven't updated it in a while. Actually, it probably wouldn't hurt if you would update all of them.

**Comment by MetalBreaker** [comment]
No, I haven't tried a different SMBIOS. Mostly because I was scared iMessage and FaceTime would stop working, and for power management.

I haven't tried a different port on my GPU, because I don't have another monitor, and this monitor only has a VGA input.

Yes, here's my config. (I removed the board ID as well, just in case) 
[config.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1822629/config.zip)



I tried doing a clean install twice, it didn't help.

No, I'm not using OsxAptioFixDrv3. I'm using AptioMemoryFix, which works better for me and allows me to access safe mode (life-saver for me). No, I'm not using EmuVariable, NVRAM works natively on my motherboard. I'm not using CsmVideoDxe because way before installing macOS, I flashed my graphics card's firmware to an UEFI-compliant one, which allowed me to completely turn off CSM in the UEFI.

I updated all my kexts and Clover before trying to update to High Sierra, so I'm positive that is not the issue. I also tried disabling every kext except FakeSMC, there was no change.

Thanks again!

**Comment by arsradu** [comment]
Well, you can simply make a copy of the current config, for testing. You can name it whatever you want and select it from Clover GUI. That so you don't work on your main config. As for iMessage and FaceTime, I think those are the least of your concerns right now. Not to mention those can be easily fixed later on. Also, you can simply disconnect from the internet during testing, if that's the problem. :) Simple, right?
You config is very clean. A bit too clean, to be honest. Is this what you're using now (aside form SMBIOS information)?
You have no Inject System ID, and you have no NvidiaWeb. Also, your SIP is fully enabled for as far as I can see. I only said to clean out the serials, since nobody is interested in that. But I'm afraid you might have cleaned more than you should. :)) Are you 100% sure this is the config you're using (again, aside from SMBIOS info).

**Comment by MetalBreaker** [comment]
That is the config I'm using.
I deleted NvidiaWeb accidentally, it was set to yes. I've never had "inject system ID" checked. SIP is disabled via csrutil, and it's disabled. I tried to disable it via clover, but it just didn't work... csrutil disable worked though. About my mac shows SIP is disabled, csrutil status shows it's disabled, and there's no "System Integrity Protection is engaged" message on startup.

**Comment by arsradu** [comment]
Hmm...I never used csrutil to disable SIP... I thought you can't do it unless you are in Recovery Mode. Which I'm not gonna do whenever I need to enable/disable it. :)) But I could be wrong.
To do it via Clover, BooterConfig needs to be set to 0x28 and CsrActiveConfig to 0x73. Not sure why it didn't work for you... I never had issues with it.
Anyway, if you already tried it this way, too, then I honestly don't know what else it could be.

**Comment by MetalBreaker** [comment]
At this point, I've tried everything. I've tried ditching DSDT GPU injection and using Clover instead, without any luck. I cannot afford a new graphics card right now and I would like to get up and running ASAP :(
