### ISSUE TITLE
Latest build kernel panics

### ISSUE THREAD

**Issue by welpo** [lvs1974/NvidiaGraphicsFixup#7]
I built the latest NvidiaGraphicsFixup and Lilu today and I got a kernel panic at boot.

Here's two pictures that hopefully are helpful:
![img_3536](https://user-images.githubusercontent.com/6399341/38165815-e9f285f6-3519-11e8-8e03-3a0a9ad3b611.jpg)
![img_3535](https://user-images.githubusercontent.com/6399341/38165816-ec037fa8-3519-11e8-804c-7f3ca355993e.jpg)

If I revert back to the builds I built on the 23rd of February, 2018, the system boots up just fine.

**My system**
Gigabyte Z370 AORUS Ultra Gaming
Intel i7 8700K
nVidia 1080Ti

Let me know if you need anything else.

**Comment by lvs1974** [comment]
Hi,
your issue seems to be very strange.
Could you do the following:

- add keepsyms=1 to boot-args 
- build & install **debug**-version of NvidiaGraphicsFixup
- get a new panic log and post it here
- if you still get panic, add -ngfxnoaudio to boot-args and try again
- try to find out a commit revision where you started to get this panic

**Comment by ReddestDream** [comment]
I encountered a similar issue about a week ago. Since then I have updated to 10.13.4, updated kexts and Clover, and made other changes to my configuration. I have not attempted to reproduce with my new configuration.

You'll find the attached panic logs have keepsyms=1 and were run with debug versions of Lilu and NvidiaGraphicsFixup with appropriate flags. I have not tested with "-ngfxnoaudio" but my display audio was working properly at the time and still is.

I found that the panic began with this commit when I attempted to test "-ngfxcompat":

https://github.com/lvs1974/NvidiaGraphicsFixup/commit/8cdb489822a61a9092d4b28e66293aec4d9c3912

After this commit, the panics occurred even without "-ngfxcompat":

https://github.com/lvs1974/NvidiaGraphicsFixup/commit/5cf39c16979c61518b8f2b9c17f237a7f1869306

Along with the panic logs, I have also attached the debug kexts I used to produce the panic logs.

I hope this is helpful. In the mean time, I am currently using NvidiaGraphicsFixup built from commit, although as I have said I have not tested to confirm that the panic still occurs for me on my new configuration on 10.13.4:

https://github.com/lvs1974/NvidiaGraphicsFixup/commit/4cf71d2827abf3b3078f386f3f235933d54c8371
[Debug Binaries.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1865942/Debug.Binaries.zip)

[Panic Logs.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1865946/Panic.Logs.zip)

**Comment by vit9696** [comment]
Thanks for the logs, they are clear in what they describe. I am also reasonably sure that the crashes are the same for both of you. Additionally I asked several users to check the kexts and they had no issues, so I am afraid the issue is at your end.

From the looks of the callstack I suspect that Lilu returns a wrong address from web driver probe symbol. If that is the case, there could be several reasons, yet all of them would be users's faults, for example:
1. NVIDIA Web Drivers are loaded from the EFI folder but are also installed in the system.
2. NVIDIA Web Drivers are installed to both /System/Library/Extensions and /Library/Extensions at once.
3. Kext cache was not updated to include the latest NVIDIA Web Driver after its installation, and contains a binary different from the one on the disk.

3 is the most likely cause, and the fix is reasonably easy: rebuild the kext cache.

In Lilu I could add (in not so close future):
1. Pointer range verification to ensure that the returned symbol at least belongs to the loaded kext.
2. Image UUID comparison to check that the loaded kext matches the kexf read from the disk.

That may detect the issue and generate a panic confirming the problem with a more descriptive message, however, NvidiaGraphicsFixup won't be able work anyway in such a case, so you kind of have to fix it no matter what.

**Comment by ReddestDream** [comment]
@vit9696 Thank you for the explanation. I tested a build of NvidiaGraphicsFixup today using the latest commit and "ngfxcompat=1" and it worked fine. The process of updating to 10.13.4, as expected, seems to have fixed my cache issues.

In the future, do you have a particular command/set of commands you suggest to rebuild the kext cache on 10.13? There seems to be a lot of confusion as to the best way . . .

**Comment by vit9696** [comment]
I suppose `kextcahe -update-volume /` or `kextcache -invalidate /` will be it.

**Comment by vit9696** [comment]
The latest commits (https://github.com/lvs1974/NvidiaGraphicsFixup/commit/7659235ff120a4c99a9a2672c86877d9c870f683 and https://github.com/vit9696/Lilu/commit/9906dbfdff72ac1ee347fe74a46fcc4fc9260213) implement both of the sanity checks I suggested above. It will unlikely crash from now on, but Lilu and the plugins will still not work properly. However, you should be able to diagnose it from the warnings like `address X is out of range` or `uuid mismatch for X`.
